### PR TITLE
Provide config for HTTP basic auth

### PR DESCRIPTION
**Pull request by srueg**

### CODE REVIEW

**Comment by ftaeger** [comment]
I don't see any reason for htaccess here ...

**Comment by srueg** [comment]
It's a [feature](https://github.com/mailhog/MailHog/blob/master/docs/Auth.md) of MailHog to provide authentication for the web interface.
Please reconsider since we would like to use this feature.

**Comment by ftaeger** [comment]
By the way: Feel free to create a fork of this project so you can maintain it yourself ;) I'm not working on this one anymore ...

**Comment by srueg** [comment]
Nice, thank you!
That's what I did. Do you think you could release one last version? :)

**Pull request merged**
